#!/bin/bash
# $IMAGE_NAME var is injected into the build so the tag is correct. 

docker build --build-arg VCS_REF=`git rev-parse — short HEAD` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  --build-arg VERSION="0.1.0" \
  --build-arg VCS_URL="https://github.com/smartcanvas/docker-web-workspace" \
  -t $IMAGE_NAME .